#include<bits/stdc++.h>
using namespace std;
int main()
{
    int a[3][3],sum0=0;
    for(int i=0;i<3;i++)
    {
        for(int j=0;j<3;j++)
        {
            cin>>a[i][j];
            sum0+=a[i][j];
        }
    }
    int a1,b1,a2,b2,a3,b3,c;
    cin>>a1>>b1>>a2>>b2>>a3>>b3>>c;
    cout<<a[a1-1][b1-1]<<endl<<a[a2-1][b2-1]<<endl<<a[a3-1][b3-1]<<endl;
    int sum=0;
    for(int i=0;i<3;i++)
    {
        for(int j=0;j<3;j++)
        {
            if(a[i][j]==0)
            {
                a[i][j]=45-sum0;
            }
        }
    }
    if(c==1)
    {
        sum=a[0][0]+a[0][1]+a[0][2];
    }
    if(c==2)
    {
        sum=a[1][0]+a[1][1]+a[1][2];
    }
    if(c==3)
    {
        sum=a[2][0]+a[2][1]+a[2][2];
    }
    if(c==4)
    {
        sum=a[0][0]+a[1][0]+a[2][0];
    }
    if(c==5)
    {
        sum=a[0][1]+a[1][1]+a[2][1];
    }
    if(c==6)
    {
        sum=a[0][2]+a[1][2]+a[2][2];
    }
    if(c==7)
    {
        sum=a[0][0]+a[1][1]+a[2][2];
    }
    if(c==8)
    {
        sum=a[0][2]+a[1][1]+a[2][0];
    }
    if(sum==6)
    {
        cout<<10000;
    }
    if(sum==7)
    {
        cout<<36;
    }
    if(sum==8)
    {
        cout<<720;
    }
    if(sum==9)
    {
        cout<<360;
    }
    if(sum==10)
    {
        cout<<80;
    }
    if(sum==11)
    {
        cout<<252;
    }
    if(sum==12)
    {
        cout<<108;
    }
    if(sum==13)
    {
        cout<<72;
    }
    if(sum==14)
    {
        cout<<54;
    }
    if(sum==15)
    {
        cout<<180;
    }
    if(sum==16)
    {
        cout<<72;
    }
    if(sum==17)
    {
        cout<<180;
    }
    if(sum==18)
    {
        cout<<119;
    }
    if(sum==19)
    {
        cout<<36;
    }
    if(sum==20)
    {
        cout<<306;
    }
    if(sum==21)
    {
        cout<<1080;
    }
    if(sum==22)
    {
        cout<<144;
    }
    if(sum==23)
    {
        cout<<1800;
    }
    if(sum==24)
    {
        cout<<3600;
    }
}